// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/routing.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetRequest struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{0}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type GreetResponse struct {
	Reply                []byte   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{1}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetReply() []byte {
	if m != nil {
		return m.Reply
	}
	return nil
}

type FibonacciRequest struct {
	N                    []byte   `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciRequest) Reset()         { *m = FibonacciRequest{} }
func (m *FibonacciRequest) String() string { return proto.CompactTextString(m) }
func (*FibonacciRequest) ProtoMessage()    {}
func (*FibonacciRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{2}
}

func (m *FibonacciRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciRequest.Unmarshal(m, b)
}
func (m *FibonacciRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciRequest.Marshal(b, m, deterministic)
}
func (m *FibonacciRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciRequest.Merge(m, src)
}
func (m *FibonacciRequest) XXX_Size() int {
	return xxx_messageInfo_FibonacciRequest.Size(m)
}
func (m *FibonacciRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciRequest proto.InternalMessageInfo

func (m *FibonacciRequest) GetN() []byte {
	if m != nil {
		return m.N
	}
	return nil
}

type FibonacciResponse struct {
	Reply                []byte   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciResponse) Reset()         { *m = FibonacciResponse{} }
func (m *FibonacciResponse) String() string { return proto.CompactTextString(m) }
func (*FibonacciResponse) ProtoMessage()    {}
func (*FibonacciResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{3}
}

func (m *FibonacciResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciResponse.Unmarshal(m, b)
}
func (m *FibonacciResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciResponse.Marshal(b, m, deterministic)
}
func (m *FibonacciResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciResponse.Merge(m, src)
}
func (m *FibonacciResponse) XXX_Size() int {
	return xxx_messageInfo_FibonacciResponse.Size(m)
}
func (m *FibonacciResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciResponse proto.InternalMessageInfo

func (m *FibonacciResponse) GetReply() []byte {
	if m != nil {
		return m.Reply
	}
	return nil
}

type GetRandomRequest struct {
	N                    []byte   `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRandomRequest) Reset()         { *m = GetRandomRequest{} }
func (m *GetRandomRequest) String() string { return proto.CompactTextString(m) }
func (*GetRandomRequest) ProtoMessage()    {}
func (*GetRandomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{4}
}

func (m *GetRandomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRandomRequest.Unmarshal(m, b)
}
func (m *GetRandomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRandomRequest.Marshal(b, m, deterministic)
}
func (m *GetRandomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRandomRequest.Merge(m, src)
}
func (m *GetRandomRequest) XXX_Size() int {
	return xxx_messageInfo_GetRandomRequest.Size(m)
}
func (m *GetRandomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRandomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRandomRequest proto.InternalMessageInfo

func (m *GetRandomRequest) GetN() []byte {
	if m != nil {
		return m.N
	}
	return nil
}

type GetRandomResponse struct {
	Reply                []byte   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRandomResponse) Reset()         { *m = GetRandomResponse{} }
func (m *GetRandomResponse) String() string { return proto.CompactTextString(m) }
func (*GetRandomResponse) ProtoMessage()    {}
func (*GetRandomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{5}
}

func (m *GetRandomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRandomResponse.Unmarshal(m, b)
}
func (m *GetRandomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRandomResponse.Marshal(b, m, deterministic)
}
func (m *GetRandomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRandomResponse.Merge(m, src)
}
func (m *GetRandomResponse) XXX_Size() int {
	return xxx_messageInfo_GetRandomResponse.Size(m)
}
func (m *GetRandomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRandomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRandomResponse proto.InternalMessageInfo

func (m *GetRandomResponse) GetReply() []byte {
	if m != nil {
		return m.Reply
	}
	return nil
}

type RelayRequest struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayRequest) Reset()         { *m = RelayRequest{} }
func (m *RelayRequest) String() string { return proto.CompactTextString(m) }
func (*RelayRequest) ProtoMessage()    {}
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{6}
}

func (m *RelayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayRequest.Unmarshal(m, b)
}
func (m *RelayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayRequest.Marshal(b, m, deterministic)
}
func (m *RelayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayRequest.Merge(m, src)
}
func (m *RelayRequest) XXX_Size() int {
	return xxx_messageInfo_RelayRequest.Size(m)
}
func (m *RelayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelayRequest proto.InternalMessageInfo

func (m *RelayRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type RelayResponse struct {
	Reply                []byte   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayResponse) Reset()         { *m = RelayResponse{} }
func (m *RelayResponse) String() string { return proto.CompactTextString(m) }
func (*RelayResponse) ProtoMessage()    {}
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{7}
}

func (m *RelayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayResponse.Unmarshal(m, b)
}
func (m *RelayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayResponse.Marshal(b, m, deterministic)
}
func (m *RelayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayResponse.Merge(m, src)
}
func (m *RelayResponse) XXX_Size() int {
	return xxx_messageInfo_RelayResponse.Size(m)
}
func (m *RelayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RelayResponse proto.InternalMessageInfo

func (m *RelayResponse) GetReply() []byte {
	if m != nil {
		return m.Reply
	}
	return nil
}

func init() {
	proto.RegisterType((*GreetRequest)(nil), "onion_routing.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "onion_routing.GreetResponse")
	proto.RegisterType((*FibonacciRequest)(nil), "onion_routing.FibonacciRequest")
	proto.RegisterType((*FibonacciResponse)(nil), "onion_routing.FibonacciResponse")
	proto.RegisterType((*GetRandomRequest)(nil), "onion_routing.GetRandomRequest")
	proto.RegisterType((*GetRandomResponse)(nil), "onion_routing.GetRandomResponse")
	proto.RegisterType((*RelayRequest)(nil), "onion_routing.RelayRequest")
	proto.RegisterType((*RelayResponse)(nil), "onion_routing.RelayResponse")
}

func init() {
	proto.RegisterFile("protofiles/routing.proto", fileDescriptor_34181ec3bf593d6c)
}

var fileDescriptor_34181ec3bf593d6c = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0xa9, 0xa0, 0xc2, 0xd9, 0xa1, 0x06, 0x1f, 0xca, 0x14, 0x2c, 0x95, 0x41, 0x7d, 0x68,
	0x07, 0xf3, 0x1b, 0x38, 0x71, 0xfa, 0x32, 0x47, 0x86, 0x08, 0x22, 0x48, 0xda, 0x9d, 0xa3, 0xd2,
	0x26, 0x35, 0x49, 0x85, 0x7d, 0x09, 0x3f, 0xb3, 0xac, 0xcb, 0xb4, 0x6b, 0xdd, 0xdc, 0x5b, 0xef,
	0xfa, 0xcf, 0x2f, 0xdc, 0xef, 0x02, 0x4e, 0x2e, 0x85, 0x16, 0x6f, 0x49, 0x8a, 0xaa, 0x2b, 0x45,
	0xa1, 0x13, 0x3e, 0x0d, 0xcb, 0x16, 0x69, 0x09, 0x9e, 0x08, 0xfe, 0x6a, 0x9a, 0x9e, 0x0f, 0xf6,
	0x40, 0x22, 0x6a, 0x8a, 0x1f, 0x05, 0x2a, 0x4d, 0x1c, 0xd8, 0xcf, 0x50, 0x29, 0x36, 0x45, 0xc7,
	0x72, 0x2d, 0xdf, 0xa6, 0xcb, 0xd2, 0xeb, 0x40, 0xcb, 0x24, 0x55, 0x2e, 0xb8, 0x42, 0x72, 0x02,
	0xbb, 0x12, 0xf3, 0x74, 0x66, 0x82, 0x8b, 0xc2, 0x73, 0xe1, 0xe8, 0x36, 0x89, 0x04, 0x67, 0x71,
	0x9c, 0x2c, 0xa1, 0x36, 0x58, 0xdc, 0xa4, 0x2c, 0xee, 0x5d, 0xc2, 0x71, 0x25, 0xf1, 0x1f, 0x6c,
	0x80, 0x9a, 0x32, 0x3e, 0x11, 0xd9, 0x5a, 0x58, 0x25, 0xb1, 0x11, 0xe6, 0x83, 0x4d, 0x31, 0x65,
	0xb3, 0xad, 0x46, 0x35, 0xc9, 0x4d, 0xc0, 0xde, 0xd7, 0x0e, 0x90, 0x87, 0xb9, 0x4d, 0xba, 0x90,
	0x39, 0x46, 0xf9, 0x89, 0x92, 0xdc, 0xc1, 0x41, 0x29, 0xca, 0x94, 0xa7, 0xe1, 0x8a, 0xf1, 0xb0,
	0xaa, 0xbb, 0x7d, 0xf6, 0xf7, 0x4f, 0x73, 0xed, 0x13, 0x90, 0x3e, 0x4b, 0xe3, 0x22, 0x65, 0x1a,
	0x7f, 0x94, 0x91, 0xf3, 0xda, 0x99, 0xba, 0xee, 0xb6, 0xbb, 0x3e, 0x60, 0xc0, 0x8f, 0x15, 0xaf,
	0xc3, 0x22, 0x8b, 0x50, 0xaa, 0x06, 0xb6, 0x2e, 0xbe, 0x81, 0x6d, 0x78, 0xef, 0xbd, 0xc0, 0x61,
	0xe9, 0x6d, 0x28, 0x26, 0x68, 0xa6, 0xbf, 0x37, 0xd2, 0xe7, 0x2d, 0x3a, 0xea, 0x37, 0x6c, 0x54,
	0x37, 0xd2, 0xb0, 0xb1, 0xb2, 0x84, 0xeb, 0xce, 0xf3, 0xc5, 0xcd, 0x38, 0x18, 0x49, 0xf1, 0x8e,
	0xb1, 0x0e, 0x4a, 0xf1, 0x81, 0x31, 0xdf, 0xfd, 0x7d, 0xee, 0xd1, 0x5e, 0xf9, 0x7d, 0xf5, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x1d, 0xd2, 0x40, 0x57, 0x03, 0x03, 0x00, 0x00,
}
