// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/routing.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DummyRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyRequest) Reset()         { *m = DummyRequest{} }
func (m *DummyRequest) String() string { return proto.CompactTextString(m) }
func (*DummyRequest) ProtoMessage()    {}
func (*DummyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{0}
}

func (m *DummyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyRequest.Unmarshal(m, b)
}
func (m *DummyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyRequest.Marshal(b, m, deterministic)
}
func (m *DummyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyRequest.Merge(m, src)
}
func (m *DummyRequest) XXX_Size() int {
	return xxx_messageInfo_DummyRequest.Size(m)
}
func (m *DummyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DummyRequest proto.InternalMessageInfo

func (m *DummyRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DummyResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyResponse) Reset()         { *m = DummyResponse{} }
func (m *DummyResponse) String() string { return proto.CompactTextString(m) }
func (*DummyResponse) ProtoMessage()    {}
func (*DummyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34181ec3bf593d6c, []int{1}
}

func (m *DummyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyResponse.Unmarshal(m, b)
}
func (m *DummyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyResponse.Marshal(b, m, deterministic)
}
func (m *DummyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyResponse.Merge(m, src)
}
func (m *DummyResponse) XXX_Size() int {
	return xxx_messageInfo_DummyResponse.Size(m)
}
func (m *DummyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DummyResponse proto.InternalMessageInfo

func (m *DummyResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*DummyRequest)(nil), "onion_routing.DummyRequest")
	proto.RegisterType((*DummyResponse)(nil), "onion_routing.DummyResponse")
}

func init() {
	proto.RegisterFile("protofiles/routing.proto", fileDescriptor_34181ec3bf593d6c)
}

var fileDescriptor_34181ec3bf593d6c = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0x2f, 0xca, 0x2f, 0x2d, 0xc9, 0xcc, 0x4b, 0xd7, 0x03,
	0x0b, 0x09, 0xf1, 0xe6, 0xe7, 0x65, 0xe6, 0xe7, 0xc5, 0x43, 0x05, 0x95, 0x34, 0xb8, 0x78, 0x5c,
	0x4a, 0x73, 0x73, 0x2b, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb8, 0xd8, 0x73,
	0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25,
	0x55, 0x2e, 0x5e, 0xa8, 0xca, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x11, 0x2e, 0xd6, 0xa2,
	0xd4, 0x82, 0x9c, 0x4a, 0xa8, 0x42, 0x08, 0xc7, 0x28, 0x98, 0x8b, 0x3b, 0x24, 0xb5, 0xb8, 0x24,
	0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x85, 0x8b, 0x1d, 0xc4, 0x0d, 0x0a, 0x70, 0x16,
	0x92, 0xd6, 0x43, 0xb1, 0x5a, 0x0f, 0xd9, 0x5e, 0x29, 0x19, 0xec, 0x92, 0x10, 0xab, 0x8c, 0x62,
	0xb8, 0xf8, 0x83, 0x52, 0x73, 0x12, 0x2b, 0xfd, 0xf2, 0x53, 0x52, 0x41, 0x26, 0xa7, 0x16, 0x09,
	0x79, 0x72, 0xf1, 0xc0, 0x85, 0x28, 0x33, 0xdd, 0x49, 0x35, 0x4a, 0xd9, 0x25, 0x58, 0x37, 0xa0,
	0x28, 0x3f, 0x2b, 0x35, 0xb9, 0x44, 0xd7, 0x1f, 0xa4, 0x52, 0x37, 0x08, 0xa2, 0x52, 0x1f, 0x11,
	0x8e, 0x49, 0x6c, 0x60, 0xb6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x94, 0x2a, 0x8f, 0x00, 0x5c,
	0x01, 0x00, 0x00,
}
